apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.20
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
    securityContext:
      runAsUser: 2000
      privileged: true
      allowPrivilegeEscalation: true

