apiVersion: v1
kind: LimitRange
metadata:
  name: limit-cpu
spec:
  limits:
  - type: Container
    max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: "100m"
      memory: 4Mi
    default:
      cpu: "300m"
      memory: "200Mi"
    defaultRequest:
      cpu: "200m"
      memory: "200Mi"
    maxLimitRequestRatio:
      cpu: "10"

